version: '3'
  
services:
  mysql:
    build: ./images/db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${MYSQL_VOLUME_PATH}:/var/lib/mysql
    ports: 
      - "${MYSQL_PORT}:3306"
  apachephp:
    build: ./images/app
    hostname: apachephp
    command: "/bin/bash -c /opt/run.sh"
    environment:
      MAGENTO_BASE_URL: ${MAGENTO_BASE_URL}
      MAGENTO_BACKEND_FRONTNAME: ${MAGENTO_BACKEND_FRONTNAME}
      MAGENTO_LANGUAGE: ${MAGENTO_LANGUAGE}
      MAGENTO_CURRENCY: ${MAGENTO_CURRENCY}
      MAGENTO_TIMEZONE: ${MAGENTO_TIMEZONE}
      MAGENTO_USE_REWRITE: ${MAGENTO_USE_REWRITE}
      MAGENTO_ADMIN_FIRSTNAME: ${MAGENTO_ADMIN_FIRSTNAME}
      MAGENTO_ADMIN_LASTNAME: ${MAGENTO_ADMIN_LASTNAME}
      MAGENTO_ADMIN_EMAIL: ${MAGENTO_ADMIN_EMAIL}
      MAGENTO_ADMIN_USER: ${MAGENTO_ADMIN_USER}
      MAGENTO_ADMIN_PASSWORD: ${MAGENTO_ADMIN_PASSWORD}
      MAGENTO_DB_NAME: ${MAGENTO_DB_NAME}
      MAGENTO_DB_HOST: ${MAGENTO_DB_HOST}
      MAGENTO_DB_USER: ${MAGENTO_DB_USER}
      MAGENTO_DB_PASSWORD: ${MAGENTO_DB_PASSWORD}
    ports:
      - "${APACHE_PORt}:80"
    depends_on:
      - mysql