version: '3'
  
services:
  mysql:
    build: ./images/db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - /opt/mysql:/var/lib/mysql
    ports: 
      - "3306:3306"
  apachephp:
    build: ./images/app
    command: "./bin/apachectl -D FOREGROUND"
    volumes:
      - /opt/magento:/opt/apache2/htdocs
    ports:
      - "80:80"
    depends_on:
      - mysql